# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: leglesslamb/lua-golang-hugo:latest

before_script:
  - pacman -Syu --noconfirm wget coreutils

cache:
  paths:
    - /apt-cache
    - /go/src/gitlab.com
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - go version
    - hugo version
    - go mod download
    - sh onedrive.sh
    - go run main.go
    - hugo
    - rm -rf public
  except:
    - master

pages:
  script:
    - go version
    - hugo version
    - go mod download
    - sh onedrive.sh
    - go run main.go
    - hugo
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
