# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: leglesslamb/lua-golang-hugo:latest

before_script:
  - pacman -Syu --noconfirm wget coreutils

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - go mod download
    - sh onedrive.sh
    - mv content_base content
    - mv templates_base templates
    - go run main.go
    - hugo
    - rm -rf public
  except:
    - master

pages:
  script:
    - go mod download
    - sh onedrive.sh
    - mv content_base content
    - mv templates_base templates
    - go run main.go
    - hugo
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
