# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: june29/golang-hugo:latest

cache:
  paths:
    - /apt-cache
    - /go/src/gitlab.com
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

post-pages:
  script:
    - go mod download
    # should be go build but I'll lowe it
    - go run main.go
