baseURL: https://utmist.gitlab.io
languageCode: en-us
title: "UTMIST: UofT Machine Intelligence Student Team"
theme: hugo-fresh

params:
  navbarlogo:
    image: logos/blueside.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    title: Clear the Mist
    subtitle: UofT Machine Intelligence Student Team
    buttontext: Join our Discord
    buttonlink: https://discord.gg/
    image: "logos/bluebottom.svg"
  navbar:
    - title: Events
      sublinks:
        - title: More Events...
          url: /events
    - title: Projects
      sublinks:
        - title: More Projects...
          url: /projects
    - title: Team
      sublinks:
        - title: Our Team
          url: /team
    - title: Alumni
      url: /team/alumni
    - title: About
      url: /about
    - title: Discord
      url: https://discord.gg/
      button: true
  footer:
    logo: white.svg
    socialmedia:
      - link: "mailto:utorontomist@gmail.com"
        icon: envelope
      - link: https://www.facebook.com/UofT.MIST/
        icon: facebook
      - link: https://github.com/utmist
        icon: github
      - link: https://gitlab.com/utmist
        icon: git
      - link: https://medium.com/@utorontomist
        icon: medium
      - link: https://twitter.com/UTMIST1
        icon: twitter
      - link: https://discord.gg/
        icon: discord
    bulmalogo: true
    quicklinks:
      column1:
        title: "Events"
        links:
          - text: Our Events
            link: /events
          - text: Organizing an Event
            link: /events/organizing
      column2:
        title: "Projects"
        links:
          - text: Our Projects
            link: /projects
          - text: Work with Us
            link: /projects/collaboration
      column3:
        title: "About Us"
        links:
          - text: About
            link: /about
          - text: Team
            link: /team
