baseURL: https://utmist.gitlab.io
languageCode: en-us
title: "UTMIST: UofT Machine Intelligence Student Team"
theme: hugo-fresh

params:
  navbarlogo:
    image: logos/blueside.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    title: Clear the Mist
    subtitle: UofT Machine Intelligence Student Team
    buttontext: Join Us
    buttonlink: /recruitment
    image: "logos/bluebottom.svg"
  navbar:
    - title: About
      url: /about
    - title: Alumni
      url: /alumni
    - title: Blog
      url: https://medium.com/@utorontomist
    - title: YouTube
      url: https://www.youtube.com/channel/UC7G_kmlXrUUvoHyfT3ZTxaw
    - title: Events
      sublinks:
        - title: More Events...
          url: /events
    - title: Projects
      sublinks:
        - title: More Projects...
          url: /projects
    - title: Team
      sublinks:
        - title: Our Team
          url: /team
    - title: Join Us
      url: /recruitment
    - title: Discord
      url: https://discord.gg/
      button: true
  section1:
    title: Clear the Mist
    subtitle: UofT Machine Intelligence Student Team
    tiles:
      - title: Events
        icon: mobile-feed
        text: Talks and workshops given by our professors and students.
        url: /events
        buttonText: Attend/Watch
      - title: Projects
        icon: laptop-cloud
        text: Student-led projects in machine intelligence.
        url: /projects
        buttonText: Get Involved
      - title: Resources
        icon: doc-sync
        text: Learning resources to help you succeed.
        url: /resources
        buttonText: Get Ahead
  footer:
    logo: white.svg
    socialmedia:
      - link: "mailto:utorontomist@gmail.com"
        icon: envelope
      - link: https://www.facebook.com/UofT.MIST/
        icon: facebook
      - link: https://github.com/utmist
        icon: github
      - link: https://gitlab.com/utmist
        icon: git
      - link: https://medium.com/@utorontomist
        icon: medium
      - link: https://twitter.com/UTMIST1
        icon: twitter
      - link: https://discord.gg/
        icon: discord
    bulmalogo: true
    quicklinks:
      column1:
        title: "Materials"
        links:
          - text: Blog
            link: https://medium.com/@utorontomist
          - text: Events
            link: /events
          - text: Projects
            link: /projects
          - text: Work with Us
            link: /projects/collaboration
      column2:
        title: "About Us"
        links:
          - text: About
            link: /about
          - text: Alumni
            link: /alumni
          - text: Team
            link: /team
          - text: Join Us
            link: /recruitment
      column3:
        title: "This Site"
        links:
          - text: Maintainers
            link: /engineering
          - text: Repository
            link: https://github.com/utmist/utmist.gitlab.io
          # - text: Wiki
          # link: https://gitlab.com/utmist/utmist.gitlab.io/-/wikis
